
# Introduction

Insomnia is a disorder related to dissatisfaction with the duration or quality of sleep. It can be a source of distress and impairment by decreasing productivity and lowering energy to engage in social activities [@americanpsychiatricassociation2013]. Prolonged exposure is associated with a higher risk of adverse outcomes on mental health [@johnson2006; @taylor2005] and cognitive functioning [@fortier-brochu2012]. 

Cognitive and behavioral models of insomnia emphasize the role of sleep-related cognitions as maintainers of insomnia. Cognitive arousal is crucial to several behavioral models of insomnia as a maintainer of the disorder [@espie2006; @harvey2002; @lundh2005; @morin1993; @ong2012; @perlis1997]. Cognitive-behavioral treatments target modifying habits, routines, and ineffective beliefs about sleep, which correlates with objective and subjective improvements in sleep [@harvey2014; @montserratsanchez-ortuno2010]. Despite its known effectiveness in insomnia treatment, some patients gain little from the cognitive-behavioral approaches [@dalrymple2010]. An alternative treatment for insomnia is Acceptance and Commitment Therapy (ACT), which also focuses on cognitions (their role rather than contents or topographies) but promotes acceptance of feelings and thoughts related to symptoms rather than control [@hayes2011acceptance]. 

Be it either approach, these non-pharmacological treatments for insomnia are an effective and reliable alternative or complement to drug therapy [@hertenstein2014; @thakral2020]. Because of that, it is also essential that valid and reliable assessment tools are available to examine the severity of symptoms or the results of an intervention, either in clinical or research settings. Two tools for assessing sleep-related cognitions are the Dysfunctional Beliefs and Attitudes about Sleep Scale (DBAS) and the Sleep Problem Acceptance Questionnaire (SPAQ). Although used widely worldwide, no study has assessed its psychometric properties with a Brazilian sample to date. Given that those measures were developed in a distinct cultural setting, it is necessary to obtain evidence for the applicability of these instruments within a specific context of a Brazilian-Portuguese-speaking population prior to usage in high-stakes settings.

## Dysfunctional beliefs and attitudes about sleep

A. G. Harvey's model [-@harvey2002] is frequently mentioned as theoretical background in investigations of cognitive processes in insomnia. It posits that the excess of negatively toned activity about sleep triggers arousal and distress, channeling attention and monitoring to sleep threats. This may create distorted perceptions of sleep and overestimation of the actual deficits during the day. To cope, the individual may engage in safety behaviors that paradoxically increase worry and preclude sleep self-correction. In Harvey's model, dysfunctional beliefs about sleep exacerbate negatively toned cognitive activity. Such beliefs are also the backbone of the Microanalytic model [@morin1993insomnia], one of the most popular models for insomnia [@marques2015].

Current evidence favors that beliefs and attitudes about sleep mediate insomnia perpetuation [@akram2020; @chow2018; @harvey2017; @lancee2019], although not all studies have found this association [@norell-clarke2021]. The Microanalytic model [-@morin1993] suggests that insomnia maintenance feeds from a cyclic process of arousal, dysfunctional cognitions, maladaptive habits, and consequences. Arousal refers to excessive emotional, cognitive, or physiologic activity, which can create core beliefs that guide information processing  [@marques2015]. Consequences may include unrealistic expectations, rigid beliefs about sleep requirements, and increased worry about the causes and consequences of sleep disturbances. Subsequent unhealthy sleep practices may include daytime napping, excessive time in bed, or indiscriminate use of sleep medication. Real or perceived consequences are linked to diminished performance during the day.

### Constructs and Their Relations

Individuals with higher insomnia symptoms are typically strong endorsers of dysfunctional beliefs about sleep [@carney2006; @cronlein2014; @eidelman2016]. Challenging those beliefs is at the core of Cognitive Behavioral Therapy for insomnia (CBT-I) [@belanger2006]. A recent meta-analysis observed clinically significant improvements in beliefs and attitudes about sleep favoring CBT-I over controls -- although, as the authors warn, those results should be interpreted with care given the low quality of evidence [@edingerjackd.2021]. Insomnia severity was identified as a risk factor for anxiety [@neckelmann2007] and depression [@blanken2020; @li2016]. Nevertheless, some suggest these relationships are the other way around [@chen2017; @jansson-frojmark2008b]. A relationship between anxiety and depression with dysfunctional beliefs about sleep is also expected: Beck's classic cognitive mechanism for the cause and maintenance of depression gives a central role to inaccurate beliefs and maladaptive information processing [@beck1979cognitive]. Displeasing memories created through exposure to adverse experiences can elicit anxiety [@brewin1996theoretical]. Thus, unrealistic attributions and expectations about sleep (or lack of sleep) may prompt anxiety-provoking thoughts. There is also evidence that dysfunctional beliefs about sleep are an indirect pathway between insomnia and depression [@sadler2013], consistent with Beck's [-@beck1979cognitive] formulation that individuals with negative cognitive styles are vulnerable to depression.

### Measurement

Morin et al. [-@morin1993insomnia] developed the Dysfunctional Beliefs and Attitudes About Sleep Scale (DBAS) to assess sleep-disruptive cognitions. The DBAS is broadly employed in experimental studies assessing sleep-related cognitions, especially the 16-item version [@thakral2020]. This instrument started as a 30-item self-report instrument rated in a 100-mm visual analog scale of agreement/disagreement. Later, Morin and colleagues [-@morin2007a] shortened it to a 16-item version and replaced the response format with a 11-point scale ranging from 0 (strongly disagree) to 10 (strongly agree). The items of the brief version were selected from the original scale based on criteria of response distribution, range, item-total correlations, and exploratory oblique factor analysis. A 4-factor structure was fitted to the 16 items in a Confirmatory Factor Analysis, labeled (a) consequences of insomnia, (b) worry about sleep, (c) sleep expectations, (d) medication, and a fifth second-order general factor. Moreover, the DBAS-16 outperformed the 30 and 10-item versions in reproducibility of factor structure, measures of internal consistency, concurrent validity, and sensitivity to change [@chungka-fai2016]. Many researchers have translated and validated the DBAS-16 across various cultures [@boysan2010; @dhyani2013; @lang2017]. These studies successfully replicated the original factor structure and presented good validity evidence.

## Acceptance of sleeping problems

Shifting from the sole focus on the cognitive processes, "third generation" behavior therapies include metacognition as a target for intervention (i.e., changing how one relates to their thoughts rather than changing their contents) [@hayes2004mindfulness]. Early models of insomnia including the metacognitive content refer to the interpretation of one's sleep patterns or consequences of poor sleep as sleep interpreting processes [@lundh2000]. These models also integrate arousal events as critical components to the causal chain that leads to insomnia. Lundh [-@lundh2005] presented the idea that insomnia originates from the inability to disengage from information processing. He further argues that cognitive deactivation is essential for sleep occurrence, and efforts of metacognitive control prevent spontaneous relaxation. Insomnia is then maintained by the mutual contribution of sleep interfering and interpreting processes. Acceptance of the naturally occurring sleep processes through adopting an adaptive stance may help reduce arousal preventing the perpetuation of this cycle [@ong2012].

### Constructs and Their Relations

The relationship between acceptance and constructs like insomnia, anxiety, and depression is similar to that expected in the cognitive behavioral model. As some theoretical models propose, insomnia is linked to a stringent attachment to sleep needs and expectations, which feeds worry, thought suppression, and rumination [@lundh2005; @ong2012]. Although there is scarce investigation of the effects of acceptance-based therapies on primary insomnia, there is promising evidence that ACT is effective in reducing the severity of insomnia and improving sleep quality in such patients [@paulos-guarnieri2022; @rash2019; @salari2020]. Review studies also summarize compelling evidence that lower levels of psychological flexibility – from which acceptance is a process – are linked to symptoms of depression and anxiety [@bai2020; @bluett2014; @ruiz2010; @twohig2017]. Additional evidence suggests that psychological inflexibility correlates with higher levels of sleep difficulty even after controlling for the effect of depressive symptoms [@kato2016].

### Measurement

The Sleep Problem Acceptance Questionnaire (SPAQ) [@bothelius2015] is the only measure of acceptance of sleep difficulties with validated scores. This instrument is an adaptation of the Chronic Pain Acceptance Questionnaire. SPAQ is gradually gaining popularity as an assessment tool in ACT-based interventions for insomnia in addition to or replacement of more general measures of acceptance [@paulos-guarnieri2022]. Ultimately, SPAQ aims to examine the role of acceptance concerning sleep quality. Its items were purposely developed to resemble similar acceptance questionnaires used in other behavioral medicine contexts. Four items compose each factor; respondents rate them on a 7-point scale, where 0 means "Disagree," and six indicates "Completely agree". SPAQ presents a two-factor structure: *Activity Engagement* and *Willingness* -- which correlates negatively (*r* = -0.26) [@bothelius2015]. *Activity Engagement* relates to persistence with normal activities despite perceived dissatisfaction with sleep, whereas *Willingness* captures the ability to give up fighting sleep problems and controlling sleep.

## The cross-cultural adaptation process

Psychologists must conduct psychometric studies of their assessment tools to prove that the scale items are good approximations of the intended construct [@mcneish2022a]. Before using an existing psychological instrument in a distinct context of how it was originally developed, it is vital to assess the construct's existence and similarity since it may manifest itself differently [@flakeConstructValidationSocial2017; @herdmanModelEquivalenceCultural1998]. A model proposed by @herdmanModelEquivalenceCultural1998 devises five types of equivalence to be assessed, namely: (1) Conceptual equivalence; (2) Item equivalence; (3) Semantic equivalence; (4) Operational equivalence; and (5) Measurement equivalence. There are many suggestions for the required steps of a cross-cultural adaptation process [@reichenheim2007]. Nevertheless, much of the published research in cross-cultural adaptation follows Beaton's [-@beaton2000] guidelines [@arafat2016].

### 1. Items translation

A minimum of two translators, fluent in both source and target language and acquainted with both cultural backgrounds, should produce the initial translation of the instrument [@borsaAdaptacaoValidacaoInstrumentos2012; @epstein2015; @geisinger1994; @reichenheim2007]. They should work independently; preferably, one translator is aware of the concepts underlying the questionnaire, while the second should have no expertise in its context and be blind or unfamiliar with it [@beaton2000]. The mixed configuration of the translation team is justified because the informed translators can find appropriate correspondences to highly domain-specific words or expressions. In contrast, naive translators are prone to choose terms closer to those used routinely by the target population.

### 2. Synthesis of the translations

Once the initial translations are completed, a committee should consider the original instrument and the translated versions and reach an agreement for a single version. Most cross-cultural adaptation guidelines suggest at least three committee members: the two initial translators and a third unbiased judge [@koller2012]. There are also suggestions that this committee can be composed of judges experts on the concepts underlying the questionnaire [@epstein2015; @guillemin1993]. Regardless, judges and authors should work together to assess the equivalence between the original version and the translations regarding semantics, idiomatic equivalence, experiential equivalence, and conceptual equivalence [@borsaAdaptacaoValidacaoInstrumentos2012]. 

### 3. Back-translation

In the back-translation phase, the synthesized version should be translated back to the source language in at least two new versions, produced by translators fluent in the source language and with a strong target language domain [@gjersing2010; @guillemin1993]. Beaton et al.'s [-@beaton2000] guideline suggests that the back-translation should precede the synthesis of the initial translations. However, @borsaAdaptacaoValidacaoInstrumentos2012 favor delaying this procedure to the last stage of the cross-cultural adaptation process, given that the translation must be thoroughly evaluated before the appreciation by the original authors. There are, therefore, different views of when one should execute this phase – or even if it is necessary, given the lack of evidence of its contribution to improving the instrument adaptation [@epstein2015; @geisinger1994; @vanwidenfelt2005]. Be that as it may, the back-translation process is a way for the original authors to assess the equivalence of meaning between the original and translated items and identifying inconsistencies or conceptual errors [@beaton2000; @borsaAdaptacaoValidacaoInstrumentos2012].

### 4. Expert committee

As hinted in previous sections, there are different views on the formation of the expert committee or when it should be called to action. Authors such as @beaton2000 suggest that the group should be composed of methodologists, health professionals, language professionals, and translators (forward and back translators) who are so far involved in the process. They also encourage carefully recording of each decision made by the committee. What underlies this phase is the assessment of aspects not yet considered, such as instrument structure, layout, instructions, and adequacy of expressions in the items [@borsaAdaptacaoValidacaoInstrumentos2012]. 

### 5. Pilot study

After completing adjustments, the instrument is ready for a pre-test with a small sample representative of the target population. For many authors, the pilot study is succeeded only by the final semantic adjustments suggested by the pre-testing sample [@beaton2000; @dortasjunior2016; @gjersing2010; @reichenheim2007; @wild2005]. The pre-testing may unveil unanticipated issues the test subjects might encounter and any divergences regarding the comprehension of item meaning and expressions as well as the test instructions [@borsaAdaptacaoValidacaoInstrumentos2012; @epstein2015; @vanwidenfelt2005]. In short, the purpose of the pre-test is to assess whether the examinees can comprehend the concept of the questions consistently and as intended by the researchers [@collins2003]. The pre-testing can be executed with a focus group -- where researchers collect the participants' impressions about the writing and content of the instrument --or through individual cognitive interviews, which allow a deeper understanding of the issues raised by the participants [@epstein2015]. Recommendations following the exact sample size for the pilot study also vary. For instance, @beaton2000 suggest probing 30 to 40 subjects. Other authors suggest more modest numbers, like 6 to 10 [@epstein2015] or 5 to 8 subjects [@wild2005]. More relevant than an exact sample size for the pilot study is that participants are a representative sample that should reflect the diversity of cultural backgrounds in the target population [@borsaAdaptacaoValidacaoInstrumentos2012].

# Objectives

The current project, therefore, aims at (a) developing a Brazilian-Portuguese translation of the Dysfunctional Beliefs and Attitudes about Sleep Scale (DBAS-16) and the Sleep Problem Acceptance Questionnaire (SPAQ), (b) examining its factorial structure, and (c) examining its construct validity.

