---
title: "Dysfunctional beliefs and psychological flexibility interplay in insomnia severity reports from a multi-centric Brazilian sample"
author: "Marwin Carmo"
date: "30/07/2021"
output:
  pdf_document: default
  html_document: default
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## North ideas

Main idea: multiple linear regression with cognitive factors as predictors of insomnia severity with depression and anxiety as control variables.

Possible question: Do levels of sleep-related cognition and acceptance predict insomnia severity, when controlling for levels of anxiety and depression?

Association between subjective insomnia severity and self report measures of insomnia acceptance and sleep related beliefs.

Pathway:

-   Why investigate sleep related cognitions and acceptance?

Discuss about cognitive model of insomnia. Introduce the role of dysfunctional beliefs and acceptance.

-   DBAS and SPAQ are associated with insomnia symptoms [@bothelius2015]

-   Why control for symptoms of anxiety and depression?

Role of acceptance and beliefs in the association with depression, anxiety and insomnia symptoms.

Depression and insomnia are known to be related either causally or otherwise. Depressive symptoms is one of the most common risk factors for insomnia. Other studies suggest that insomnia is a risk factor for depressive symptoms [@kato2016].

-   They are relevant predictors of insomnia (reference)
-   Related to the two cognitive measures?

## Draft

Acceptance and commitment therapy (ACT) is a form of intervention based on helping the patient achieve a new form of experiencing thoughts and feelings. ACT comprehends mindfulness, acceptance and cognitive diffusion [@salari2020].

ACT is known as one of the third wave treatments and originates from the cognitive behavioral therapy (CBT), which increases psychological flexibility.

On the whole, ACT is performed with the aim of mental training, increasing motivation, psychological flexibility and self-efficacy in an individual.

As a person with insomnia tries to control his or her thoughts and feelings, his or her insomnia is exacerbated.

Dysfunctional beliefs was a significant mediator of change in insomnia severity post CBT-I intervention [@lancee2019]

## Ong et al 2012 model

people with insomnia hold maladaptive beliefs and attitudes about sleep. maladaptive behaviors and arousal producing cognitions are dysfunctional responses to poor sleep and daytime fatigue and these resposnses maintain the disorder by creating a vicious cycle of insomnia

Without the flexibility to allow competing thoughts to be considered (e.g., “I can find other ways to cope if I get less than 8h”), secondary arousal becomes a mechanism by which insomnia is perpetuated. Together, both primary and secondary arousals are seen as factors that promote and maintain the insomnia disorder.

Lundh (2005) also presented the idea that mindfulness and acceptance skills might facilitate “cognitive deactivation” which is similar to the concept of reducing secondary arousal.

Metacognitive models promote a shift in mental processes (second order) rather than a direct change of the mental contents or behaviors (first order). Metacognitive process are implicit in other modes of insomnia, including the loss of automaticity, selective attention given to sleep and the interpretative value of negative beliefs and attitudes about sleep.

Instead of changing a thought or behavior, greater awareness promotes a metacognitive shift toward a more objective, non-judging stance.

Measures of acceptance, mindfulness, and experiential avoidance were evaluated collectively as a proxy for psychological flexibility. Findings showed that psychological inflexibility was a significant predictor of insomnia severity, problems with sleep and rest, low sleep efficiency, and fatigue.

People with insomnia also tend to be very rigid in their thinking and behaviors. In assessing sleep-related cognitions, people with insomnia tend to hold onto fairly rigid beliefs about sleep

The unwillingness to accept sleeplessness results in the very suffering that they are attempting to alleviate by causing secondary arousal.

With equanimity, one is adopting a stance of nonattachment to sleep outcomes, which facilitates improved emotion regulation in the face of insufficient sleep and fatigue. It also refers to letting go of the strong belief in contingencies between sleep and daytime functioning. The shift toward equanimity is a shift from outcome-oriented
thinking to process-oriented thinking.

Nonattachment from this perspective does not imply a lack of feelings or emotions, but rather it suggests creating a space between a stimulus and the reaction to the stimulus. For example, letting go ofthe need to sleep 8 h per night does not mean that one should no longer have thoughts about sleep needs. Rather, these thoughts shift toward how one feels at the present moment, and the recognition that thoughts about sleep are just that; thoughts about sleep, and nothing more, allowing the secondary arousal to dissipate.

## References
