---
title: "Association between sleep-related cognitions and insomnia symptomns. Evidence from a multi-centric Brazilian sample."
author: "Marwin M. I. B. Carmo"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
bibliography: psicologia_sono.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction (2 paragraphs)

Insomnia sufferers are a group characterized for frequent complaints about quality and quantity of sleep, difficulties in initiating and maintaining sleep and early-morning awakenings with inability to return to sleep [@diagnost2013]. Psychological disorders like anxiety and depression are known to co-occur with symptoms of insomnia and are possible aggravating factors for sleep problems [@belanger2016]. Evidence suggests that the relationship between anxiety and depression with insomnia are bidirectional, meaning that both poses as risk factors for insomnia and sleep alterations increases risk for emotional disturbances [@riemann2020].



Depression and insomnia are comorbid and have a bidirectional relationship. Anxiety increases ruminative thoughts. Both contribute to reinforcement of dysfunctional beliefs and low acceptance. Or may have also a bidirectional relationship, with negative thoughts enhancing depression and anxiety symptoms. Dysfunctional beliefs affect insomnia in this and this way, according to some models. Recently acceptance has been investigated.

Link para ansiedade e depressão e depois mecanismos psicológicos

### Objectives (1 paragraph)

## Method (1 paragraph)

## Results (2 paragraphs)

## Conclusion (1 paragraph)

## References
