---
title: "Revisão Sistemática e Meta Análise: Uma Abordagem Prática"
author: 
  - "Marwin M I B Carmo"
  - "Professor: André Brunoni"
date: "25/08/2021 - 08/11/2021"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aula 01 - Prática e Teórica

## A01. Vídeo 02 – Por que fazer uma RS e uma MA?

Critérios **FINER**: Feasible, Interesting, Novel, Ethics, Relevant

- Feasible 

Já exite um número de ensaios clínicos suficiente que justificam fazer uma RV ou MA?

Pelo menos 5 ensaios clínicos de MA de desfecho principal e 3 ou mais de desfecho secundário.

Também se deve pensar no numero adequado de sujeitos para conduzir a RS. Há várias etapas que vão precisar de mais de uma pessoa para rever os artigos. Por vezes uma terceira pessoa para chegar a um consenso. 

Tem que ser facctível em termos de tempo (principalmente), dinheiro e escopo (as vezes vale a pena restringir o escopo).

- Interesting

Relevante para pesquisadores e para policymakers.

## A01. Vídeo 03 – Diferenças entre RSs e MAs

Overview = Umbrella review

Scoping review: estágio preliminar da evidência. 


#### Não-sistemática:

- A pergunta é não-específica;
- A estratégias de busca não é definida previamente;
- Critérios de seleção ausentes;
- A qualiade dos artigos incluídos **não** é verificada;
- A síntese dos resultados é **qualitativa**

#### Sistemática

- A pergunta é focada;
- A estratégias de busca é definida previamente e deve ser reprodutível para outro autor;
- Critérios de seleção claramente definidos;
- A qualiade dos artigos incluídos é verificada;
- A síntese dos resultados é **quantitativa** (meta-análise)

## A01. Vídeo 04 – Bibliografia e artigos recomendados.

Sites recomendados:

*Cochrane Handbook for Systematic Reviews of Interventions*

*GRADE Handbook*

*CONSORT*: padronização para reportar RCT

# Aula 02 - Teórica (30/08/2021)

## A02. Vídeo 1- Critérios PICO

Criterios PICO descrevem ou detalham o próprio objetivo do estudo

Qual é o objetivo de sua RS e MA?

> Avaliar se o remédio/tratamento/terapêutica/intervenção "A" "funciona" para a doença/condição/transtorno "X"?

**P**acientes  
**I**ntervenções  
**C**omparações  
**O**utcomes/Desfechos (tempo)

### Participantes

Ex: 

- Geral: Pacientes com depressão

Com um critério aberto, a busca será muito maior, temos muito mais estudos para incluir. O resultado do desfecho terá mais heterogeneidade . Por outro lado, ganha uma grande generalização dos resultados.

- Específico: depressão primária, unipolar, em adultos, da atenção primária...

A restrição é maior. Pode dar uma resposta mais clara para aquela subpopulação. Pode acabar não conseguindo chegar ao final do estudo pela grande especificidade. Pode ter uma baixa generalização.

Validade interna (específica) e Validade extena (geral/ ampla).

Não há certo nem errado, depende dos objetivos da revisão.

**Critérios que foram desenvolvidos a posteiori** (por ex: incluir apenas estudos que usaram o DSM-5). Acaba excluindo outros estudos mais antigos que não usaram essa classificação.

**Análises de subgrupos**: Dados "misturados" (ex: apenas para idosos, apenas para pacientes graves). Caso se espere modificação do efeito

## A02. Vídeo 2- PICO (Intervenções)

Uma resposta maior, mais abrangente, pode ser mais interessante, mas é mais complexa e mais difícil de ser executada. Também pode ser mais difícil de ser interpretada. Em um primeiro momento, pode ser mais interessante focar em perguntas mais específicas.

Certas intervenções farmacológicas (por ex. anticoagulantes)

Tratamento é ativo (por ex. cirurgia, fisioterapia)

Maioria das intervenções não-farmacológicas vai exigir certo cuidado. Vai ser preciso elaborar um pouco mais na hora de pensar nas intervenções. É necessário detalhar mais as intervenções

Combinação de intervenções:

- A combinação em si pode ser o mais interessante (ex: fisioterapia associada com estimulação elétrica);
- A de interesse mais "alguma coisa". Admitindo todas as intervenções de interesse, estando associadas ou não;
- Pode ser o caso de só querer incluir a monoterapia

Tratamento depende da adesão

## A02. Vídeo 3- PICO (Comparações)

A MA envolve a **comparação entre dois grupos no mínimo** ou entre mais de dois grupos. Envolve uma dicotomia, seguir uma MA "pairwise" (ou várias meta-analises de 1x1) ou uma Network Meta Analysis (ex: 4 grupos ao mesmo tempo, todos contra todos).

Experimental vs Controle (TAU, waiting list, no treatment, experimental vs. placebo). Placebo pode ser ativo (produz efeitos colaterais) ou inerte ("pílula de farinha").

A vs B

Modalidades diferentes de intervenção: Dose alta vs. Dose baixa, ou IV vs. outras formas de adm

Comparação entre dois grupos ou mais (MA "pairwise"; NMA)

A x B x C

A x B x P

## A02. Vídeo 4- PICO (Outcomes)

Deve ser definido já no desenho do estudo quais serão os desfechos investigados (primário e secundário).

- Desfechos **contínuos**: *ordinais* (ex: mudança em uma escala de dor ou depressão) ou *discretos* (mudança em um parâmetro físico ou laboratorial; conservam uma relação numérica muito clara entre eles. ex: pressão arterial, peso).

- Desfechos **binários**: Morte; Evento clínico (gravidez, infarto...); Dado originário de uma escala (resposta > 50% melhora, obesidade imc > 30); Eventos de contagem.

A definição dos critérios construto tem que ser definida nos desfechos, mesmo que seja algo mais abrangente.

- Importância dos desfechos (desfechos intermediários)

- Quando foi coletado (endpoint)
  - "Clinically meaningful": de acordo com o que eu defino
  - Primeiro assessment
  - Last assessment: interessante se quero avaliar um efeito mais duradouro da intervenção
  - De acordo com a definição do estudo: considero tempos diferentes de acordo com o estudo

- Como foi coletado
  - Expertise do coletador
  - Instrumento: o entrevistador aplica ou é autoaplicável?
  - Forma de coleta
  - Tecnologia utilizada: considerando muitas possíveis, gera heterogeneidade que tem que ser tratada na análise estatística

- Número de desfechos: normalmente mais de um
  - Primário: acceptability (quantas pessoas sairam do estudo no grupo ativo e no grupo placebo; ve a aceitabilidade), efeitos adversos, desfecho clínico
  - Secundário: resposta, remissão, melhora no curto e longo prazo, melhora em outras escalas...

- 2 PICOS
  - PICO inicial
  - PICO final
  - Não é recomendado que a mudança seja feita após a meta-analálise pois pode parecer que mudou a pergunta em função dos resultados estatísticos.

## A02. Vídeo 5- Onde Procurar (Parte 1)

Os critérios PICO serão a base tanto da procura quanto da definição dos critérios de inclusão e exclusão.

### Onde procurar

Bases de busca

1. PubMed/Medline: base de dados (onde os artigos ficam disponíveis para serem procurados) pública e gratuita.

2. ISI Web of Knowledge (Web of Science): é uma base que também pega artigos que ainda não foram publicados (como anais de congressos, capítulos de livro etc).

3. Embase (Elsevier)

4. CENTRAL (Cocrhane)

## A02. Vídeo 6- Onde Procurar (Parte 2)

Literatura cinzenta (dados não-publicados)

Estágio:

- Anais de congressos;  
- "Engavetados";  
- Em andamento;  
- Revisão/publicação

Onde procurar:

- Contato com especialistas;  
- clinicaltrials.gov;  
- Dados da indústria;  
- Dados de agências públicas;  
- Anais de congresso;  
- Repositório de teses;  
- Citações

Situações especiais:

- Online vs. impresso;  
- Pre-print: é interessante incorporá-los e fazer análises de sensibilidade.

## A02. Vídeo 7- Estratégia de Busca (Parte 1)

Sensibilidade vs. especificidade: o recomendado é ser o mais sensível possível no começo. Começar abrangente e depois ir sendo filtrado

O que precisa ser a priori é a estratégia de busca, os termos podem ir sendo refinados. Estamos testando diferentes estratégias de busca... depois rever isso

## A02. Vídeo 8- Estratégia de Busca (Parte 2)

Sempre anotar a data em que a revisão foi feita.

### Sintaxe

- PubMed
  - Operadores boleanos: AND (interseção entre os termos), OR (funciona como uma "soma" dos termos), NOT (tirar a interseção com algum termo)
  - ""
  - \*
  - $
  - ( )
  - termos MeSH: classificação que o MedLine faz para delimitar os keywords relacionados e não precisar pesquisar tudo
  - [ti], [tiab]

## A02. Vídeo 9- Estratégia de Busca (Parte 3)

### Organização da revisão

Etapa de filtragem dos resultados da busca.

Melhor salvar os resultados e fazer a busca por outro software do que buscar direto no PubMed, pois os resultados podem mudar de um dia para o outro.

1. Método arcaico

Os resultados da busca podem ser salvos como arquivo `.csv` para serem abertos em outro software (como Excel) para refinar a busca. O primeiro screening se faz pelo título. É recomendado primeiro filtrar o título e depois o abstract.

2. Endnote

3. Rayyan

## A02. Vídeo 10- Estratégia de busca para situações específicas

### Situações específicas

Duplicatas: aparecem quando se começa a juntar banco de dados.

Publicação contendo mais de um ensaio: Por algum motivo, uma publicação colocou resultados de dois ensaios clínicos. A unidade é o ensaio, e não a publicação.

Informações complementadas/ retificadas em correspondências.

Estudos fraudulentos e retratados.

Anciliarry studies: Uma série de estudos adicionais contendo informações que não couberam no estudo principal. Tem que ser utilizada as informações do estudo original e não dos estudos auxiliares.

## A02. Vídeo 11- Critérios de exclusão e inclusão

As causas de exclusão devem ser anotadas. Normalmente são relacionadas ao **PICO**: outros tipos de participantes, outros tipos de intervenção, outros tipos de comparação e outros tipos de desfecho.

Dados em duplicata.

Outros tipos de artigo: cartas ao editor, editoriais, outras RS/MAs

Estudos pré-clínicos (estudos em animais)

Motivos **errados** para exclusão

Não ser em língua inglesa não é um bom motivo para exclusão. O ideal é tentar traduzir o artigo.

Potencialmente dados de interesse não-publicados. É preciso tentar contatar os autores e esgotar todas as outras fontes

Estudos cross-over: a pessoa começa recebendo um tratamento e na metade do tratamento passa para o outro. É possível utilizar dados pelo menos da primeira parte do estudo.

Critérios/ procedimentos que variam entre os países ou recursos

Desenhos que podem ser incluidos:

- ECRs: paralelos, cross-over, fatoriais e não-inferioridade  
- ECs abertos  
- Estudos pré/pós

Se o campo já estiver relativamente maduro, vale a pena incluir apenas ECRs. Se for a primeira ou a segunda MA, vale a pena incluir os estudos mais fracos (ECs abertos e pré-pós)

## A04. Vídeo 01 - Ensaios Clínicos (Parte 1)

### Avaliação da qualidade de um ensaio clínico

Três pilares dos ensaios clínicos:

- Aleatorização: grupos divididos ao acaso  
- Mascaramento  
- Experimentação (intenção de tratamento)

**Validade interna**: resultados observados são verdadeiros, livres de vieses e refutando-se explicações alternativas. Alta validade interna fornece chance alta de provavelmente refletir a realidade. 

Vieses da validade interna:

- Aleatorização:
  - Previne interferências dos investigadores na alocação dos tratamentos;
  - Produz grupos de tratamento comparáveis para fatores de risco conhecidos e desconhecidos;
  - Garante a inferência estatística dos testes. Não precisa das correções como nos testes de coorte.

Proporção da alocação

- A proporção normalmente é 1:1  
- A alocação não balanceada é justificável caso uma intervenção seja mais cara, mais acessível ou placebo  
- Proporção 3:2 ou 2:1 é relativamente eficiente  

## A04. Vídeo 02 - Ensaios Clínicos (Parte 2)

Mascaramento é diferente de aleatorização.

A **aleatorização** oculta do investigador/ participante o grupo do próximo participante.

O **mascaramento** oculta do investigador/ participante o gurpo que o participante atual está alocado.

Aleatorização facilita o mascaramento, e vice-versa.

Estudos quase-experimentais são não-aleatorizados mas podem ser mascarados.

A ausência do mascaramento pode comprometer a adesão dos participantes, avaliação do desfecho pelos pesquisadores e análise estatística.

Análise de intenção de tratamento: considera as pessoas mesmo com dados faltantes. É como foi planejado o estudo e o que importa é o que aconteceu na vida real.

Em estudos de não-inferioridade a análise por protocolo é preferível.

**Validade Externa**: avaliação sobre a representatividade da amostra estudada em relação à população.

## A04. Vídeo 03 - Validade Interna - Aleatorização e Alocação

Um estudo terá validade interna se tiver baixo risco de viés.

Estudos com alto viés não são eliminados. Prefere-se rodar uma MA só com os estudos de baixo viés e verifica se o resultado é diferente quando é feito com todos.

- Vieses de seleção
  - Alocação não-aleatoizada: lista de randomização feita de uma maneira inadequada (ex: verificação do registro do paciente (par/ ímpar));
  - Alocação não oculta: seria como escrever para os participantes qual foi a sequencia de alocação. Um processo clássico é o SNOSE e Alocação central para contornar.
  - Grupos desbalanceados no baseline

## A04. Vídeo 04 - Validade Interna - Mascaramento

Viés de "assignment"

- Participantes;  
- Pessoal (staff);  
- "Interventores"

## A04. Vídeo 05 - Validade Interna - Protocolo do estudo

Desvio de protocolo: checar os protocolos de todos os estudos incluidos para posteriormente verificar se existe algum tipo de viés.

Viés de relato seletivo

#### Viés geral

- Baixo: maioria das informações vêm de baixo risco

- Indeterminado: maioria das informações vêm de baixo/ indeterminado risco

- Alto: um número importante vem de alto risco

## A04. Vídeo 06- Validade Interna – Intervenção

Não tem uma resposta única para o máximo de dropout tolerado. Pode depender do objeto ou desenho de estudo, pois alguns são mais propensos a ter perdas.

## A04. Vídeo 07 - Instrumentos de Avaliação de Viés

Instrumentos estruturados **não são mais recomendados** atualmente: JDAD (quanto mais pontos tiver, melhor a qualidade) e PEDRO

Risk-of-Bias tool: 5 domínios

- Randomização  
- Intervenção  
- Falta de dados de desfecho  
- Mensuração do desfecho  
- Resultados reportados

## A05. Vídeo 01 – Como extrair os dados (Parte 1)

- Instrumento de coleta de dados

Podem ser desenvolvidos formulários para sistematizar como os dados são extraídos (ex: Google Forms, Redcap).

Planilhas de Excel/ Word

Softwares comerciais: SRDR (systematic review data repository)

- Extração de dados em duplicata (mais de uma pessoa)

Para os desfechos principais é obrigatório extrair os dois de maneira independente. Para outras características do estudo que não sejam as principais, é recomendado.

- Procurar material suplementar: Não esquecer de baixar junto com o artigo, pois em muitas vezes vai ter a informação de interesse.

- Mais de um timepoint: mais de um tempo do desfecho principal pode ser de interesse. A definição do fim pode variar.

- Ver se vai extrair dados de *intention to treat* ou *por protocolo*. O recomendado é o ITT, mas, eventualmente, podem ser extraidos os dois dados. Se tiver número suficiente, pode ser extraído tanto dados do ITT quanto do PP.

## A05. Vídeo 02 – Como extrair os dados (Parte 2)

- Extração de dados

Desfechos: são as variáveis mais importantes, por isso o ideal é ter dois revisores extraindo de forma independente.

Tipos de desfecho: contínuo (em cada grupo: M, DP, n; pré e pós), categórico/ binário (em cada grupo: N total (n com e n sem desfecho); apenas pós (não começa com ninguem com o evento)), extração direta dos efeitos (por ex, OR, HR, contrast, marginal means) (podem estar em tabelas, figuras)

Primários e secundários: subgrupos, escalas usadas, efeitos adversos, outros secundários de eficácia.

Demais variáveis: altamente recomendável mas não obrigatório

Informações para análise qualitativa: Randomização, allocation, mascaramento, ITT vs. PP (tecnica para missing data), inconsistência, indirecteness, imprecisão, vieses (limitações, como viés de instumento, recall bias), dados não reportados (selective outcome reporting), ver e comparar protocolo original no clinicaltrials, critérios de inclusão/ exclusão (PICO)

## A05. Vídeo 03 – Como extrair os dados (Parte 3)

- Dados incompletos

Ausência de média: se for reportado a mediana, é aceitável que se utilize essa medida como substituta. Em muitos casos, o que será apresentado é a mudança e não a média do segundo ponto (como diferença ou porcentagem).

Ausência do desvio padrão: Pode ser calculado pelo IC 95%, EP, p-valor, IQR. Se não for reportado nada que permita estimar, pode ser imputado usando SD de outros ECs e/ou MAs

## A07. Vídeo 03 – Atribuição de peso aos estudos

Efeitos fixos: todo erro padrão observado em cada estudo será unicamente baseado no erro padrão daquele estudo. Na realidade não tem outra caracteristica do estudo que não o tamanho dele. Diz que o efeito real é o mesmo para todos os estudos; a estimativa vai ser diferente, mas na realidade há o mesmo efeito.

Efeitos aleatórios: existe uma distribuição de efeitos verdadeiros, e não depende somente do padrão da amostra mas também de um erro aleatório.

Os efeitos fixos vão valorizar pouco estudos pequenos e mais os estudos grandes. Os efeitos aleatórios tendem a distribuir melhor e a lidar melhor com heterogeneidade.

Nos efeitos fixos, como os grandes estão dominando, temos um IC pequeno. Nos efeitos aleatórios o IC é maior.

Na prática, quase sempre se escolhe efeitos aleatórios.

## A07. Vídeo 04 – Interpretação dos resultados

Avaliação da **heterogeneidade**: É importante pois o verdadeiro efeito pode ser diferente. Haver vieses nos ECRs. eventualmente invalidar os resultados.

É medido com o $I^2$ e $\chi^2$.

Não tem parâmetros bem definidos, mas quanto maior, pior (mais heterogeneidade).

Análise subgrupo: avaliar se houve diferença nos estudos entre a qualdiade deles

Meta-regressão: regredir de acordo com outras variáveis (ver a razão da heterogeneidade)

Random-effects: Normalmente "melhor", mas eventualmente "pior" se houver sugestão de publication bias/ small study effects. Pode aumentar o viés dos estudos menores por valorizar eles.

## A09

### GRADE

Tem uma proposta mais abrangente, não se propõe apenas a falar de RS e MA. Se propõe a avaliar toda sorte de estudos secundários e até primários.

Se propõe a ser disponível para um público menos especialista

Validade interna: Risco baixo, risco indeterminado (não penaliza ou diminui 1 nível), risco alto (diminui 1 nível ou diminui 2 níveis).

Inconsistência: avalia a heterogeneidade dos resultados (forest plot)

Imprecisão: ICs largos por estudos com baixo poder estatístico (resultado final do que foi obtido na MA)

Evidência indireta: Adequação do PICO

Viés de publicação: publicação seletiva dos resutlados que fornece uma estimativa aumentada ou diminuída dos resultados.

**Características de interesse para avaliação da Imprecisão**

O IC é grande, mas não é estabelecido o que é considerado grande.

Leva em conta se o total de pacientes de todos os estudos é maior do que o n estimado de um estudo ideal (calculado com poder adequado para obter um poder de amostra adequado)

Poucos estudos

Amostras pequenas nos estudos

Desfechos pouco comuns (raros)

Com base nestes critérios, pode ser reduzido em 0, 1 ou 2 níveis. 

Se atingiu o N mínimo (OIS) ou se o N é alto. Se o IC sobrepõe, rebaixa a nota. Se não atingiu, rebaixa a nota em 1 ou 2 níveis dependendo do número ideal e se cruzou o IC ou não.

**Indirectness**: propõe avaliar se a pergunta do estudo é respondida pela RS ou MA. Compara o PICO ideal com o PICO real

**Inconsistência**: Avalia a heterogeneidade, se há ou não diferença entre os estudos da RS.

- Metodológica: diferentes amostras, diferentes desenhos, diferentes intervenções, diferentes comparações

## A10

### A10. Video 01 - MA estudo observacional

Quase-experimentais: são randomizados mas podem ser mascarados. Por exemplo, o avaliador não sabe qual é a intervenção.

Estudos observacionais: não tem intervenção

- Caso-controle: Olha para o passado. Ve pessoas com e sem a doença e vai olhar para trás para ver se essas pessoas foram expostas a exposição ou fatores de risco.

- Prevalência: Olha para o presente. Ve o corte de um determinado momento e associar quem foi exposto e tem a doença vs quem não foi exposto e não tem a doença. Análise por razão de chances.

- Coorte: olha para o futuro. Começa a partir de pessoas sem doenças e depois de um tempo ve quantas pessoas desenvolveram a doença dentre as que foram expostas e as que não foram. A medida é o risco relativo.

São úteis para avaliar exposições de longo tempo, complexas, em grupos vulneráveis e/ou que intervenção não seria ética

- Problemas:

A variável de confusão é um dos principais problemas do desenho do estudo.

Não foram desenhados para avaliar efeito de intervenção/ exposição em questão. Não é atualizada. Não é corrigida para múltiplas comparações.

Ausência de randomização: grupos são difererntes, sujeito a viés de confusão. 

Ausência de mascaramento: efeito "saudável" de participar da coorte.

Ausência de intervenção experimental: tratamento/ exposição flutua naturalmente com o tempo.

Análises costumam ser ajustadas/utilizam métodos complexos: aumento da heterogeneidade. Cada coorte faz uma analise diferente, controlando para diferentes efeitos.

Estudos/ análises não costumam ser registradas previamente: viés de publicação costuma ser muito alto. Funnel plot mais "extremo" para estudos pequenos.

Não existem ferramentas bem definidas para avaliar a qualidade dos estudos observacionais. Um deles é o STROBE.

Dados necessários podem não estar relatados para os fins da RS e MA: necessidade de requisitar novas análises, muitas vezes complexas, aos autores.

Peso assimétrico para coortes grandes: importância maior do que RCTs ou CC.

Estudos publicados ao longo de várias décadas: pode ter efeito de mudanças nas características e hábitos de população.

- Possíveis soluções

Estudos observacionais são exploratórios, MAs destes também: a evidência fica pendente do ensaio clínico. Não indica intervenções/ tratamentos; pode indicar necessidade de RCTs; harmonização de coortes (juntar os dados individuais da coorte e ajustar pelos mesmos critérios/ avaliações ao longo do tempo, para ter estimativas mais precisas).

Ajuste para variáveis de confusão são necessários: o viés vai ser maior ainda se não ajustar vs ajustar.

Muitas análises de subgrupos: baseados em: desenho do estudo; duração (exposição) de tratamento; ano de publicação; tipo de tratamento; qualidade dos estudos

Preferir random-effects: incorpora melhor heterogeneidade, tirando peso excessivo de estudos muito grandes

Funnel plot separado por desenho

Ter cuidado maior na descrição dos achados

### A10. Vídeo 03 – Umbrella review

Se propõe a fazer um sumário de um amplo escopo de evidência, indo além do que uma RS ou MA tem a oferecer.

- Para que serve?

Diversas intervenções para a mesma população;

Diferentes maneiras de aplicar uma intervenção, para a mesma população;

Mesma intervenção, diferentes populações.

- Para que não serve?

Avaliar ECRs (e não RS): a unidade é a RS;

Utilizar técnicas de MA: a umbrella review é narrativa em relação a apresentação dos resultados.

- Quando é adequada?

Revisão rápida e user-friendly da literatura. Não investiga nada muito profundo (por exemplo, diferenças entre genero ou efeitos colaterais). É focada para um público não especialista na área;

RS estão atualizadas. É um dos estados mais maduros da literatura onde há um grande volume de evidências.

- Conceitos e difereças de US e RS

Objetivos: estudos primários (ECRs) vs RSs

Seleção: Critérios de inclusão e exclusão/ qualidade de ECRs vs Rs.

Qualidade das RSs: A princípio não é possível incluir todas, pois as mais novas vão repetir evidências das mais antigas. Dados sobrepostos: i) incluir apenas as RSs do grupo Cochrane; ii) incluir todas as RSs e evitar contar dados sobrepostos; iii) incluir todos as RSs e contar todos os dados (vai gerar uma imensa repetição do mesmo achado); iv) O **melhor** é selecionar as RSs mais recentes, de maior qualidade, mais relevantes, mais compreensivas, com maior N, de acordo com critérios a priori (é boa mas nem sempre é a solução ideal).

- Coleta de dados: ECRs vs Rs

- Análise quantitativa

Não há analise quantitativa na UR. É uma descrição; evitar comparações entre as RSs;

Certeza da evidência;

Síntese da evidência: Conversão da medida de tamanho do efeito.

### A10. Video 07 - MA de dados individuais

É o contraste entre dados agrupados (aggregated data) e independent data. Temos acesso a todos os dados individuais de cada estudo, permetindo homogeneizar de acordo com os critérios de eligibilidade.

- Problemas da MA AD

Tamanhos do efeito: é baseado simplesmente em média, desvio padrão, tamanho amostral, ou variáveis binárias. Funciona bem quando queremos estimativas pontuais do efeito. Gera dificuldade em fazer meta-regressão. Como o caso é o estudo, a meta-regressão não leva em conta os tamanhos amostrais individuais, fazendo com que haja pouco poder estatístico.

PICO: Grande heterogeneidade nos critérios mesmo que se entenda que foi feita uma tentativa de homogeneização nas etapas da MA e RS. Os critérios de inclusão/exclusão serão diferentes entre estudos; alguns estudos podem ter doses diferentes; a duração do tratamento também pode ser diferente entre estudos.

Análise dos dados: Os estudos podem ter utilizados técnicas diferentes de missing data/ imputação; análises estatísticas diferentes; diferentes medidas de desfecho.

- Soluções que a IPD fornece

Permite utilizar os mesmos critérios de inclusão/ exclusão.

Seleção de timepoints semelhantes. Mesmo tempo em todos os estudos.

Imputação própria de missing data.

Meta-regressão mais precisa.

Maior poder para detectar resultados.

Padronização das medidas de efeito.

- Problemas da IPD

Colaboração de todos os envolvidos.

Compartilhamento de dados e segurança.

Não supera problema de baixa qualidade dos dados originais.

Análises estatísticas mais complexas. Análise estatística: i) one-stage (mixed-effect multilevel regression com todos os indivíduos de todos os estudos), ii) two-stage (em cada estudo: regressões simpes para obter estimativas de efeito -> técnica convencional de MA posteriormente).

### A10. Vídeo 06 – MA de rede (Network MA)

Permite comparação simultânea de +2 grupos. 

O network plot une vários tatamentos entre si. Permite comparações diretas e indiretas. A linha é o número de estudos e o círculo o tamanho da evidência.

- 3 princípios:

**Transitividade**: Cada nó (tratamento) tem que estar falando de populações semelhantes. Há transitividade se variáveis clínicas e demográficas que estão relacionadas com o desfecho (definido a priori) são mais ou menos homogêneas. Garante que a comparação de tratamentos indiretos via nós é válida. É violada quando modificadores de efeito são diferentes entre os estudos.

**Heterogeneidade**: Intra estudos/comparações pairwise e indireta.

**Consistência (coerência)**: se tamanho de efeitos diretos e indiretos são semelhantes.

