---
title: "Association between sleep-related cognitions and insomnia symptomns. Evidence from a multi-centric Brazilian sample."
author: "Marwin M. I. B. Carmo"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
bibliography: psicologia_sono.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction (2 paragraphs)

Insomnia sufferers are a group characterized for frequent complaints about quality and quantity of sleep, difficulties in initiating and maintaining sleep and early-morning awakenings with inability to return to sleep [@diagnost2013]. Psychological disorders like anxiety and depression are known to co-occur with symptoms of insomnia and are possible aggravating factors for sleep problems [@belanger2016]. Evidence suggests that the relationship between anxiety and depression with insomnia is bidirectional, meaning that both poses as risk factors for insomnia and sleep alterations increases risk for emotional disturbances [@riemann2020].

Excess of negatively toned cognitive activity about sleep may maximize worries and ruminative thoughts increasing arousal and an anxiety state shifts attention to sleep-related threats [@harvey2002].The cognitive-behavioral model of insomnia proposes that arousal, cognitions, behaviors, and perceived consequences play an important role in maintaining insomnia symptoms [@morin1993]. People with insomnia tend to hold dysfunctional beliefs and maladaptative behaviors in response to sleep problems which are proxies for the cognitive arousal that feeds the cycle of insomnia.

The metacognitive model of insomnia expands the previous model by defining cognitive activity as primary arousal and how one interprets those thoughts as a secondary arousal. Primary and secondary processes mutually influence each other in respect that the content of maladaptative sleep-related thoughts can have a greater negative impact in the maintenance of insomnia disorder if one is rigidly attached to them [@ong2012].

### Objectives (1 paragraph)

## Method (1 paragraph)

## Results (2 paragraphs)

## Conclusion (1 paragraph)

## References
