---
title: "Motivation letter"
output: pdf_document
---

I am in my final year of a MEng Aerospace Engineering degree at The University of Manchester and am writing to apply for your graduate engineer training scheme. I heard about Falcon Aircraft through attending a presentation on campus and after meeting your representative, Matthew Turner, I was convinced I wanted to work for your company. I am passionate about having a career in the aerospace industry, as I’ve really enjoyed my degree and am eager to build on the technical and leadership skills I have gained. I want to work specifically for your company because I am impressed by the structure of your graduate scheme; the opportunity for rapid career progression, guidance from a corporate mentor and support in gaining professional qualifications will enable me to achieve my professional goals and contribute as effectively as I can to Falcon Aircraft and the wider aerospace engineering industry. I can offer skills and experience which meet your requirements. I gained commercial experience when I undertook a year in industry working for Airways Ltd., assisting on a new engine design project. During my degree I developed practical and technical skills and an understanding of aerospace design. I used my problem-solving, team working and creativity skills in individual and group projects and presentations. From my CV you will notice that my overall degree mark was a 2:2. I transferred to the University of Manchester to study Aerospace Engineering after my first year at Hull University studying Maths. I had to cover first year and second year work during the year and I found it a challenge to manage my increased work load. However, during my final year, I was able to improve my time management skills and achieved a good 2:1 for the year, including a 70% mark for my dissertation project on engine design. I hope that my genuine enthusiasm for this opportunity comes through and you are persuaded that I have the skills to make a strong contribution to Falcon Aircraft. I am available for interview at any time, and look forward to hearing from you.